### ISSUE TITLE
Failed to parse message file

### ISSUE THREAD

**Issue by Carter12s** [Carter12s/roslibrust#129]
When testing today on calculon I tripped the following tests:

```
test test::generate_ok_on_ros1 ... FAILED
test test::generate_ok_on_ros2 ... FAILED

failures:

---- test::generate_ok_on_ros1 stdout ----
thread 'test::generate_ok_on_ros1' panicked at 'Failed to parse a literal value in a message file to the corresponding rust type: /bond_disable_heartbeat_timeout to String', roslibrust_codegen/src/gen.rs:262:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::generate_ok_on_ros2 stdout ----
thread 'test::generate_ok_on_ros2' panicked at 'Failed to parse a literal value in a message file to the corresponding rust type: /bond_disable_heartbeat_timeout to String', roslibrust_codegen/src/gen.rs:262:85

```

Appears to be caused by this message: http://docs.ros.org/en/diamondback/api/bond/html/msg/Constants.html

From this package:
https://wiki.ros.org/bond

Not sure how it made it on my system, but we should add it as an adversarial test case and support it.

**Comment by Carter12s** [comment]
God the documentation on how this "should work" is really bad:
![image](https://github.com/Carter12s/roslibrust/assets/8097919/0d69cabe-59d3-40b2-8992-c6b5c2f134b6)

**Comment by Carter12s** [comment]
Oh and ROS1 and ROS2 disagree with each other:
![image](https://github.com/Carter12s/roslibrust/assets/8097919/99735144-42dd-4955-8888-486823fb8c9e)
